// <copyright file="Program.cs" company="Logan Foster">
// 11754587
// </copyright>

namespace Spreadsheet_Logan_Foster
{
    /// <summary>
    /// Our autogenerated Program class.
    /// </summary>
    internal static class Program
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        [STAThread]
        /// <summary>
        /// Our Main method.
        /// </summary>
        static void Main()
        {
            // To customize application configuration such as set high DPI settings or default font,
            // see https://aka.ms/applicationconfiguration.
            ApplicationConfiguration.Initialize();
            Application.Run(new Form1());
        }
    }
}